apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
spec:
  type: ClusterIP
  selector:
    app: airflow-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080