apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler-deployment
  labels:
    app: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: airflow_image
        imagePullPolicy: Never
        command:
            - airflow
            - scheduler
        envFrom:
            - configMapRef: 
                name: airflow-config-map
